name: task_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  dotted_border: ^2.0.0+3
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/board.jpg
  uses-material-design: true
